import { useCallback, useEffect, useMemo, useState } from 'react';
import { expenses } from '@/api/modules';
import { api } from '@/api/client';
import DataGrid from '@/components/DataGrid.jsx';
import {
  ConfirmDialog,
  EmptyState,
  ErrorNotice,
  FormErrorSummary,
  Modal,
  Spinner,
} from '@/components/ui.jsx';
import {
  CheckboxField,
  ModeSwitch,
  PageHeader,
  StatCard,
  Tabs,
  TextAreaField,
  TextField,
} from '@/components/FormControls.jsx';
import { useToast } from '@/components/Toast.jsx';
import {
  countErrors,
  validateFields,
  focusFirstInvalid,
} from '@/components/formValidation.js';

const money = (v) =>
  v == null ? '—' : Number(v).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const day = (v) => (v ? new Date(v).toLocaleDateString() : '—');

const EMPTY = {
  name: '',
  date: new Date().toISOString().slice(0, 10),
  expenseType: '',
  details: '',
  comments: '',
  amount: '',
  tax: '',
  tds: '',
  finalAmount: '',
  regular: '0',
};

/**
 * Society expenses — full parity with Society2024/society_expense.aspx.
 *
 * Covers: the expense form with auto-calculated final amount, the regular /
 * add-on switch, the approver selection grid, the approvals view, and the
 * filtered expense list. The invoice number is generated by the SP.
 */
/* What Submit insists on, in the shape validateFields expects. */
const EXPENSE_FIELDS = [
  { name: 'name', label: 'Expense name', required: true },
  { name: 'date', label: 'Date', required: true },
];

export default function SocietyExpensePage() {
  const [rows, setRows] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [busy, setBusy] = useState(false);
  const [search, setSearch] = useState('');
  const [tab, setTab] = useState('all');

  const [form, setForm] = useState(null);
  const [confirming, setConfirming] = useState(null);
  const toast = useToast();
  // name -> message, for the fields the last submit found empty.
  const [fieldErrors, setFieldErrors] = useState({});
  const [approvers, setApprovers] = useState([]);
  const [selectedApprovers, setSelectedApprovers] = useState([]);
  const [formTab, setFormTab] = useState('details');

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await expenses.list(search ? { search } : undefined);
      setRows(data.items ?? []);
    } catch (err) {
      setError(err);
    } finally {
      setLoading(false);
    }
  }, [search]);

  useEffect(() => {
    load();
  }, [load]);

  // Approver candidates come from the vendor-bill form data, which exposes the
  // same add_approver branch the legacy page used.
  useEffect(() => {
    api
      .get('/accounts/vendor-bills/form-data')
      .then((d) => setApprovers(d.approvers ?? []))
      .catch(() => {});
  }, []);

  /** Final amount = amount + tax - TDS, recalculated as the legacy page did. */
  const computedFinal = useMemo(() => {
    if (!form) return 0;
    return Number(form.amount || 0) + Number(form.tax || 0) - Number(form.tds || 0);
  }, [form]);

  const setField = (key) => (e) => {
    setFieldErrors((prev) => (prev[key] ? { ...prev, [key]: undefined } : prev));
    const { value } = e.target;
    setForm((prev) => ({ ...prev, [key]: value }));
  };

  const openCreate = () => {
    setForm({ ...EMPTY });
    setSelectedApprovers([]);
    setFormTab('details');
    setError(null);
  };

  const openEdit = (row) => {
    setForm({
      id: row.expense_id,
      name: row.ex_name ?? '',
      date: row.date ? String(row.date).slice(0, 10) : '',
      expenseType: row.ex_type ?? '',
      details: row.ex_details ?? '',
      comments: row.comments ?? '',
      amount: row.amount ?? '',
      tax: row.tax ?? '',
      tds: row.tds ?? '',
      finalAmount: row.f_amount ?? '',
      regular: row.type === 'Regular' ? '0' : '1',
    });
    setSelectedApprovers([]);
    setFormTab('details');
    setError(null);
  };

  /*
   * Only the rules a per-field check cannot express stay here — the empty
   * checks moved to EXPENSE_FIELDS so they report against the box at fault
   * rather than as one sentence naming one field at a time.
   */
  const validate = () => {
    if (Number(form.amount || 0) <= 0) return 'Amount must be greater than zero';
    return null;
  };

  const onSubmit = async (event) => {
    event.preventDefault();

    const missing = validateFields(EXPENSE_FIELDS, form);
    setFieldErrors(missing);
    if (Object.keys(missing).length) {
      setError(null);
      focusFirstInvalid(EXPENSE_FIELDS, missing);
      return;
    }

    const message = validate();
    if (message) {
      setError(new Error(message));
      return;
    }

    setBusy(true);
    setError(null);
    try {
      const body = {
        name: form.name,
        date: form.date,
        expenseType: form.expenseType,
        details: form.details,
        comments: form.comments,
        amount: Number(form.amount || 0),
        tax: Number(form.tax || 0),
        tds: Number(form.tds || 0),
        finalAmount: computedFinal,
        regular: Number(form.regular),
      };
      const wasEdit = Boolean(form.id);
      if (wasEdit) await expenses.update(form.id, body);
      else await expenses.create(body);
      setForm(null);
      await load();
      toast.success(`Expense ${wasEdit ? 'updated' : 'recorded'} successfully.`, { title: 'Saved' });
    } catch (err) {
      setError(err);
      toast.error('The expense could not be saved. Please check the form and try again.');
    } finally {
      setBusy(false);
    }
  };

  const visible = useMemo(() => {
    if (tab === 'regular') return rows.filter((r) => r.type === 'Regular');
    if (tab === 'addon') return rows.filter((r) => r.type === 'Add-On');
    return rows;
  }, [rows, tab]);

  const totals = useMemo(
    () => ({
      count: visible.length,
      amount: visible.reduce((s, r) => s + Number(r.f_amount || 0), 0),
    }),
    [visible],
  );

  const columns = [
    { key: 'invoice_no', label: 'Invoice' },
    { key: 'date', label: 'Date', render: day },
    { key: 'ex_name', label: 'Expense' },
    { key: 'ex_details', label: 'Details' },
    { key: 'type', label: 'Type' },
    { key: 'amount', label: 'Amount', align: 'right', render: money },
    { key: 'f_amount', label: 'Final', align: 'right', render: money },
    { key: 'expense_status', label: 'Status' },
  ];

  return (
    <section>
      <PageHeader title="Society expenses" subtitle={`${totals.count} expense(s) · ${money(totals.amount)}`}>
        <input
          className="field-input w-56"
          placeholder="Search expenses…"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          aria-label="Search expenses"
        />
        <button type="button" className="btn-primary" onClick={openCreate}>
          Add expense
        </button>
      </PageHeader>

      <div className="mb-4 grid gap-3 sm:grid-cols-3">
        <StatCard label="Expenses" value={totals.count} />
        <StatCard label="Total value" value={money(totals.amount)} />
        <StatCard
          label="Regular / add-on"
          value={`${rows.filter((r) => r.type === 'Regular').length} / ${rows.filter((r) => r.type === 'Add-On').length}`}
        />
      </div>

      <Tabs
        tabs={[
          { id: 'all', label: 'All', count: rows.length },
          { id: 'regular', label: 'Regular', count: rows.filter((r) => r.type === 'Regular').length },
          { id: 'addon', label: 'Add-on', count: rows.filter((r) => r.type === 'Add-On').length },
        ]}
        active={tab}
        onChange={setTab}
        className="mb-4"
      />

      {!form ? <ErrorNotice error={error} onRetry={load} /> : null}

      <div className="card overflow-hidden">
        <DataGrid
          columns={columns}
          rows={visible}
          idKey="expense_id"
          loading={loading}
          exportName="society-expenses"
          emptyTitle="No expenses recorded"
          actions={(row) => (
            <>
              <button type="button" className="btn-secondary" onClick={() => openEdit(row)}>
                Edit
              </button>
              <button
                type="button"
                className="btn-danger"
                onClick={() =>
                  setConfirming({
                    title: 'Delete expense',
                    message: `Delete ${row.invoice_no}?`,
                    run: () => expenses.remove(row.expense_id),
                  })
                }
              >
                Delete
              </button>
            </>
          )}
        />
      </div>

      <Modal
        open={Boolean(form)}
        title={form?.id ? 'Edit expense' : 'Add expense'}
        onClose={() => setForm(null)}
        footer={
          <>
            <button type="button" className="btn-secondary" onClick={() => setForm(null)} disabled={busy}>
              Cancel
            </button>
            <button type="submit" form="expense-form" className="btn-primary" disabled={busy}>
              {busy ? 'Saving…' : 'Save expense'}
            </button>
          </>
        }
      >
        {form ? (
          <form id="expense-form" onSubmit={onSubmit} noValidate>
            <FormErrorSummary count={countErrors(fieldErrors)} />
            <Tabs
              tabs={[
                { id: 'details', label: 'Expense details' },
                { id: 'approvers', label: 'Approvers', count: selectedApprovers.length },
              ]}
              active={formTab}
              onChange={setFormTab}
              className="mb-4"
            />

            {formTab === 'details' ? (
              <div className="space-y-4">
                <div className="grid gap-4 sm:grid-cols-2">
                  <TextField
                    label="Expense name"
                    name="name"
                    required
                    error={fieldErrors.name}
                    value={form.name}
                    onChange={setField('name')}
                  />
                  <TextField
                    label="Date"
                    name="date"
                    type="date"
                    required
                    error={fieldErrors.date}
                    value={form.date}
                    onChange={setField('date')}
                  />
                  <TextField
                    label="Expense type"
                    name="expenseType"
                    value={form.expenseType}
                    onChange={setField('expenseType')}
                  />
                  <ModeSwitch
                    label="Expense category"
                    options={[
                      { value: '0', label: 'Regular' },
                      { value: '1', label: 'Add-on' },
                    ]}
                    value={form.regular}
                    onChange={(v) => setForm((p) => ({ ...p, regular: v }))}
                  />
                </div>

                <TextAreaField
                  label="Details"
                  name="details"
                  rows={2}
                  value={form.details}
                  onChange={setField('details')}
                />
                <TextAreaField
                  label="Comments"
                  name="comments"
                  rows={2}
                  value={form.comments}
                  onChange={setField('comments')}
                />

                <div className="grid gap-4 border-t border-slate-200 pt-4 sm:grid-cols-4">
                  <TextField
                    label="Amount"
                    name="amount"
                    type="number"
                    step="0.01"
                    required
                    value={form.amount}
                    onChange={setField('amount')}
                  />
                  <TextField
                    label="Tax"
                    name="tax"
                    type="number"
                    step="0.01"
                    value={form.tax}
                    onChange={setField('tax')}
                  />
                  <TextField
                    label="TDS"
                    name="tds"
                    type="number"
                    step="0.01"
                    value={form.tds}
                    onChange={setField('tds')}
                  />
                  <TextField
                    label="Final amount"
                    name="finalAmount"
                    value={money(computedFinal)}
                    readOnly
                    hint="Amount + tax − TDS"
                  />
                </div>

                {!form.id ? (
                  <p className="text-xs text-slate-500">
                    The invoice number is generated automatically when the expense is saved.
                  </p>
                ) : null}
              </div>
            ) : (
              <div>
                {approvers.length === 0 ? (
                  <EmptyState title="No approvers available" hint="Add committee members first." />
                ) : (
                  <div className="space-y-2">
                    <p className="mb-3 text-sm text-slate-600">
                      Select who must approve this expense.
                    </p>
                    {approvers.map((a) => (
                      <CheckboxField
                        key={a.user_id}
                        label={a.name}
                        checked={selectedApprovers.includes(a.user_id)}
                        onChange={() =>
                          setSelectedApprovers((p) =>
                            p.includes(a.user_id) ? p.filter((x) => x !== a.user_id) : [...p, a.user_id],
                          )
                        }
                      />
                    ))}
                  </div>
                )}
              </div>
            )}

            <div className="mt-4">
              <ErrorNotice error={error} />
            </div>
          </form>
        ) : null}
      </Modal>

      <ConfirmDialog
        open={Boolean(confirming)}
        title={confirming?.title}
        message={confirming?.message}
        busy={busy}
        onCancel={() => setConfirming(null)}
        onConfirm={async () => {
          setBusy(true);
          try {
            await confirming.run();
            await load();
            toast.success('Expense deleted successfully.', { title: 'Deleted' });
          } catch (err) {
            setError(err);
            toast.error(err?.message ?? 'The expense could not be deleted. Please try again.');
          } finally {
            setBusy(false);
            setConfirming(null);
          }
        }}
      />
    </section>
  );
}
