// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'basicinfo.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BasicInfo _$BasicInfoFromJson(Map<String, dynamic> json) => BasicInfo(
      contactNo: json['contact_no'] as String?,
      name: json['name'] as String?,
      ownerId: (json['owner_id'] as num?)?.toInt(),
      login: json['login'] as String?,
      societyId: json['society_id'] as String?,
      type: json['type'] as String?,
      flatNo: json['flat_no'] as String?,
      preMob: json['pre_mob'] as String?,
      relation: json['relation'] as String?,
      email: json['email'] as String?,
      unit: json['Unit'] as String?,
      sqFt: json['sq_ft'] as String?,
      dob: json['dob'] as String?,
      jobTitle: json['job_title'] as String?,
      flatId: (json['flat_id'] as num?)?.toInt(),
      buildId: (json['build_id'] as num?)?.toInt(),
      wingId: (json['wing_id'] as num?)?.toInt(),
      gender: json['gender'] as String?,
      profileImage: json['profile_image'] as String?,
      language: json['language'] as String?,
      maskPhone: (json['mask_phone'] as num?)?.toInt(),
      maskEmail: (json['mask_email'] as num?)?.toInt(),
      shareGate: json['share_gate'] as String?,
      homeNo: json['home_no'] as String?,
      societyName: json['society_name'] as String?,
      buildName: json['build_name'] as String?,
      buildAddress: json['build_address'] as String?,
      loginStatus: (json['login_status'] as num?)?.toInt(),
      token: json['token'] as String?,
      activeStatus: (json['active_status'] as num?)?.toInt(),
      appNotify: (json['app_notify'] as num?)?.toInt(),
      callNotify: (json['call_notify'] as num?)?.toInt(),
      documents: json['docs_path'] as String?,
      documentName: json['doc_name'] as String?,
      uploadDate: json['upload_date'] as String?,
      docType: json['doc_type'] as String?,
      docPath: json['doc_path'] as String?,
      documentId: (json['document_id'] as num?)?.toInt(),
    );

Map<String, dynamic> _$BasicInfoToJson(BasicInfo instance) => <String, dynamic>{
      'name': instance.name,
      'owner_id': instance.ownerId,
      'login': instance.login,
      'society_id': instance.societyId,
      'type': instance.type,
      'flat_no': instance.flatNo,
      'pre_mob': instance.preMob,
      'email': instance.email,
      'Unit': instance.unit,
      'profile_image': instance.profileImage,
      'sq_ft': instance.sqFt,
      'dob': instance.dob,
      'job_title': instance.jobTitle,
      'flat_id': instance.flatId,
      'build_id': instance.buildId,
      'wing_id': instance.wingId,
      'gender': instance.gender,
      'language': instance.language,
      'mask_phone': instance.maskPhone,
      'mask_email': instance.maskEmail,
      'share_gate': instance.shareGate,
      'home_no': instance.homeNo,
      'society_name': instance.societyName,
      'build_name': instance.buildName,
      'build_address': instance.buildAddress,
      'login_status': instance.loginStatus,
      'token': instance.token,
      'active_status': instance.activeStatus,
      'app_notify': instance.appNotify,
      'call_notify': instance.callNotify,
      'contact_no': instance.contactNo,
      'relation': instance.relation,
      'docs_path': instance.documents,
      'doc_name': instance.documentName,
      'upload_date': instance.uploadDate,
      'doc_type': instance.docType,
      'doc_path': instance.docPath,
      'document_id': instance.documentId,
    };
