// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'due_History.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

DueHistory _$DueHistoryFromJson(Map<String, dynamic> json) => DueHistory(
      n_M_Id: (json['n_m_id'] as num?)?.toInt(),
      owner_Id: (json['owner_id'] as num?)?.toInt(),
      receipt_Id: (json['receipt_id'] as num?)?.toInt(),
      date: json['date'] as String?,
      total_Amount: (json['total_amount'] as num?)?.toDouble(),
      type: json['type'] as String?,
      due_Date: json['due_date'] as String?,
      due_Name: json['due_name'] as String?,
      receipt_No: json['receipt_no'] as String?,
      bill_No: (json['bill_no'] as num?)?.toInt(),
      build_Id: (json['build_id'] as num?)?.toInt(),
      build_Name: json['build_name'] as String?,
      wing_Id: (json['wing_id'] as num?)?.toInt(),
      w_Name: json['w_name'] as String?,
      address1: json['address1'] as String?,
      address2: json['address2'] as String?,
      print_Name: json['print_name'] as String?,
      registration_No: json['registration_no'] as String?,
      pay_Mode_Name: json['pay_mode_name'] as String?,
      chqno: json['chqno'] as String?,
      remarks: json['remarks'] as String?,
      society_Id: json['society_id'] as String?,
      flat_No: json['flat_no'] as String?,
      name: json['name'] as String?,
      received_Amt: (json['received_amt'] as num?)?.toDouble(),
      email: json['email'] as String?,
      building_Wing: json['Building_wing'] as String?,
      dob: json['dob'] as String?,
      pre_Mob: json['pre_mob'] as String?,
      society_Name: json['society_name'] as String?,
      full_Name: json['Full_name'] as String?,
      chqdate: json['chqdate'] as String?,
      timestamp: json['timestamp'] as String?,
      billId: (json['bill_id'] as num?)?.toInt(),
      billType: (json['bill_type'] as num?)?.toInt(),
      paidAmount: (json['paid_amount'] as num?)?.toDouble(),
      unit: json['unit'] as String?,
      payMode: json['pay_mode'] as String?,
      status: json['status'] as String?,
      transaction: json['transaction'] as String?,
      billStatus: json['bill_status'] as String?,
      amount: (json['amount'] as num?)?.toDouble(),
      billRef: json['bill_ref'] as String?,
      transactionRef: json['transaction_ref'] as String?,
      billno: json['Billno'] as String?,
      due: (json['due'] as num?)?.toDouble(),
      seenStatus: (json['seen_status'] as num?)?.toInt(),
      notifyStatusId: (json['notify_status_id'] as num?)?.toInt(),
      taxInterestAmt: (json['tax_interest_amt'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$DueHistoryToJson(DueHistory instance) =>
    <String, dynamic>{
      'n_m_id': instance.n_M_Id,
      'owner_id': instance.owner_Id,
      'receipt_id': instance.receipt_Id,
      'date': instance.date,
      'total_amount': instance.total_Amount,
      'amount': instance.amount,
      'bill_ref': instance.billRef,
      'type': instance.type,
      'due_date': instance.due_Date,
      'due_name': instance.due_Name,
      'receipt_no': instance.receipt_No,
      'bill_no': instance.bill_No,
      'build_id': instance.build_Id,
      'build_name': instance.build_Name,
      'wing_id': instance.wing_Id,
      'w_name': instance.w_Name,
      'address1': instance.address1,
      'address2': instance.address2,
      'print_name': instance.print_Name,
      'registration_no': instance.registration_No,
      'pay_mode_name': instance.pay_Mode_Name,
      'chqno': instance.chqno,
      'remarks': instance.remarks,
      'society_id': instance.society_Id,
      'flat_no': instance.flat_No,
      'name': instance.name,
      'received_amt': instance.received_Amt,
      'email': instance.email,
      'Building_wing': instance.building_Wing,
      'dob': instance.dob,
      'pre_mob': instance.pre_Mob,
      'society_name': instance.society_Name,
      'Full_name': instance.full_Name,
      'chqdate': instance.chqdate,
      'timestamp': instance.timestamp,
      'bill_id': instance.billId,
      'bill_type': instance.billType,
      'paid_amount': instance.paidAmount,
      'unit': instance.unit,
      'pay_mode': instance.payMode,
      'status': instance.status,
      'transaction': instance.transaction,
      'bill_status': instance.billStatus,
      'transaction_ref': instance.transactionRef,
      'Billno': instance.billno,
      'due': instance.due,
      'seen_status': instance.seenStatus,
      'notify_status_id': instance.notifyStatusId,
      'tax_interest_amt': instance.taxInterestAmt,
    };
