import 'package:json_annotation/json_annotation.dart';

part 'expense_request.g.dart';

/// Body of POST/PUT /api/web/accounts/expenses.
///
/// The invoice number is generated by sp_society_expense on insert, so it is
/// never sent. `finalAmount` is what the society actually pays — the server
/// stores amount, tax and tds separately and does not recompute it.
@JsonSerializable(includeIfNull: false)
class ExpenseRequest {
  /// ISO yyyy-MM-dd.
  @JsonKey(name: 'date')
  final String? date;

  @JsonKey(name: 'expenseType')
  final String? expenseType;

  @JsonKey(name: 'name')
  final String name;

  @JsonKey(name: 'details')
  final String? details;

  @JsonKey(name: 'comments')
  final String? comments;

  @JsonKey(name: 'amount')
  final double amount;

  @JsonKey(name: 'tax')
  final double? tax;

  @JsonKey(name: 'tds')
  final double? tds;

  @JsonKey(name: 'finalAmount')
  final double finalAmount;

  /// 1 marks a recurring expense head.
  @JsonKey(name: 'regular')
  final int? regular;

  const ExpenseRequest({
    required this.name,
    required this.amount,
    required this.finalAmount,
    this.date,
    this.expenseType,
    this.details,
    this.comments,
    this.tax,
    this.tds,
    this.regular,
  });

  factory ExpenseRequest.fromJson(Map<String, dynamic> json) =>
      _$ExpenseRequestFromJson(json);

  Map<String, dynamic> toJson() => _$ExpenseRequestToJson(this);
}
