// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVD6hUSK4zMfG43bMjyjwTFmTz5PJc_qk',
    appId: '1:303424747645:web:b75ea40a11efa9b810d914',
    messagingSenderId: '303424747645',
    projectId: 'society-management-32053',
    authDomain: 'society-management-32053.firebaseapp.com',
    storageBucket: 'society-management-32053.firebasestorage.app',
    measurementId: 'G-F3FR0WH1LF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_5FB8lo-CPi-c3L3d0q6cMLKmxPArrcw',
    appId: '1:303424747645:ios:fba36135c330886110d914',
    messagingSenderId: '303424747645',
    projectId: 'society-management-32053',
    storageBucket: 'society-management-32053.firebasestorage.app',
    iosBundleId: 'com.example.societyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_5FB8lo-CPi-c3L3d0q6cMLKmxPArrcw',
    appId: '1:303424747645:ios:fba36135c330886110d914',
    messagingSenderId: '303424747645',
    projectId: 'society-management-32053',
    storageBucket: 'society-management-32053.firebasestorage.app',
    iosBundleId: 'com.example.societyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVD6hUSK4zMfG43bMjyjwTFmTz5PJc_qk',
    appId: '1:303424747645:web:dc143cf2ed2e247410d914',
    messagingSenderId: '303424747645',
    projectId: 'society-management-32053',
    authDomain: 'society-management-32053.firebaseapp.com',
    storageBucket: 'society-management-32053.firebasestorage.app',
    measurementId: 'G-63Y026HPB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8A2M9losZ197diDmAgfILZT7pibTw308',
    appId: '1:303424747645:android:e1f5c2990cf5746d10d914',
    messagingSenderId: '303424747645',
    projectId: 'society-management-32053',
    storageBucket: 'society-management-32053.firebasestorage.app',
  );

}